Ревью №1
VitalyBibik/sprint12 pull request #1
Opened 2020-04-30 12:51 UTC by VitalyBibik

2020-05-01 08:09 UTC, mrprovoker requested changes
Добрый день!

Работа в целом хорошая, большинство проверок реализованные роуты проходит. Но есть несколько критичных замечаний.


**Надо исправить:**
- Если запустить `eslint --ext=.js ./`, исключая проверку директорий node_modules и public, то будет 29 ошибок линтинга. Ошибок быть не должно.
- Некорректно обрабатывается POST-запрос `http://localhost:3000/users/123`. Сейчас ответ приходит в виде HTML, а ожидается ответ в виде JSON: `{ message: 'Запрашиваемый ресурс не найден' }`. Аналогично и DELETE, PATCH и другие не GET-запросы. 
- Согласно заданию:
> если пользователя с запрошенным идентификатором нет, API должен возвращать 404 статус ответа и JSON: { "message": "Нет пользователя с таким id" }

Сейчас приходить ответ со статусом 400.
- Когда пользователь найден, то должен приходить объект с данными пользователя без дополнительного поля в объекте, сейчас приходит: `{ "userSend": ... }`
- Отсутствует заполненное README в ветке `develop`. Рекомендованный минимум: заголовок проекта, небольшое описание и инструкция как развернуть проект


Можно лучше:
- Модули в package.json:
```
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-plugin-import": "^2.20.2",
```
имеют отношение только к разработки и должны находится в секции `devDependencies`.
- Рекомендуется заполнить description в package.json
- Рекомендуется подключение модулей (require) всегда указывать в начале файла. Сейчас в `app.js` блок подключения прерывается объявлением переменных таких как `const { PORT = 3000 } = process.env;`




**Важно:** сейчас пулл реквест открыт из ветки master в develop.

При правках данный pull request необходимо смержить. Все правки необходимо сделать в ветке develop. Потом открыть пулл реквест из develop в master и далее отправить ссылку на открытй пулл реквест.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-05-01 13:21 UTC, VitalyBibik commented
Добрый день :)
У меня пару вопросов есть исходя из ошибок,
1) res.status(404).json({ message: 'Запрашиваемый ресурс не найден' });
Если читать доку (http://expressjs.com/en/5x/api.html#res.json) то так приходит ответ в формате json
2)   8:19  error  Unexpected dangling '_' in '_id'  no-underscore-dangle
  9:38  error  Unexpected dangling '_' in '_id'  no-underscore-dangle
От этих ошибок я смогу избавиться если поменяю исходный массив с данными юзеров и поменяю там поле _id На id, тогда мне не придется писать так в проверке, чтобы она верно выполнялась

2020-05-01 14:58 UTC, mrprovoker commented
> Если читать доку (http://expressjs.com/en/5x/api.html#res.json) то так приходит ответ в формате json

По коду сейчас корректный JSON приходит только для GET-запросов.  Если отправить POST запрос на `http://localhost:3000/users/123` будет HTML.
Подробнее про маршрутизацию различных видов запросов можно прочитать [тут](https://expressjs.com/ru/guide/routing.html)

> Unexpected dangling '_' in 'id' no-underscore-dangle

Правила eslint можно [отключать](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) для конкретных строк. Для данной ошибки необходимо именно отключить правило, чтобы не ругалось.

2020-05-02 12:04 UTC, VitalyBibik commented
https://github.com/VitalyBibik/sprint12/pull/2
Создал новый пулл исходя из "Можно лучше"

2020-05-15 00:39 UTC, merged