new version
VitalyBibik/sprint12 pull request #2
Opened 2020-05-02 12:02 UTC by VitalyBibik

Переделал то что было описано в 1 пулл реквесте, спасибо за статью про роуты) Надеюсь, сейчас сделал верно :)

2020-05-02 12:03 UTC, VitalyBibik commented
https://github.com/VitalyBibik/sprint12/pull/1

2020-05-03 06:45 UTC, mrprovoker requested changes
Спасибо за правки.

Теперь ошибок eslint нет, большинство замечаний было исправлено. К сожалению не было исправлено одно критичное замечание.


**Надо исправить:**
- Некорректно обрабатывается POST-запрос `http://localhost:3000/users/123`. Сейчас ответ приходит в виде HTML, а ожидается ответ в виде JSON: `{ message: 'Запрашиваемый ресурс не найден' }`. Аналогично и DELETE, PATCH и другие не GET-запросы. 

Проблема в записи: 
```
app.get('*', (req, res) => {
  res.status(404).json({ message: 'Запрашиваемый ресурс не найден' });
});
```

То есть согласно записи, у app вызывается метод `get`, поэтому сейчас обрабатываются только GET-запросы. Необходимо заменить на `all`.


При правках данный pull request закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же pull request'е.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-05-03 08:58 UTC, VitalyBibik commented
Поправил, не заметил, что не исправил в app

2020-05-03 09:27 UTC, mrprovoker approved these changes
Спасибо за правки. Теперь все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!

2020-05-06 16:50 UTC, merged