Develop sprint14
VitalyBibik/sprint12 pull request #8
Opened 2020-05-31 18:04 UTC by VitalyBibik

Добрый день, в прошлом спринте делал дополнительные задания в этом постарался их сделать тоже :) + читал отдельный блок в тренажере и попытался использовать то, что там советуют, но не выносил пароль в отдельный файл .env и не выносил в переменную среды. Сделал для этого файла config.js. 
Сейчас пока каша в голове и работа происходила по принципу читаю доку, пишу как там 👯 .

2020-06-01 11:14 UTC, aarefiev requested changes
Хорошая работа. Выполнено дополнительное задание :+1:.

Хорошее описание проекта. Проект хорошо структурирован, элементы сгруппированы в группы по принадлежности (роуты, контроллеры, модели, мидлвары). Для статической проверки синтаксиса подключен линтер `eslint`, устанавливающий соответствие стайлгайду _Airbnb_. Запуск линтера завершается без ошибок. Есть отдельный конфигурационного файла со всеми настройками для работы сервера. В схеме модели `User` ошибка. Роуты настроены корректно, согласно заданию. Централизованная обработка несуществующего роута есть, работает. Мидлвара авторизации есть, но не используется. Сервер локально запускается без дополнительной настройки, ошибок в консоли не возникает. Временные файлы игнорируются.

Ниже представлен список ошибок и улучшений. Развернутые комментарии непосредственно в коде.

**Нужно исправить:**
1. Не игнорируются временные файлы.
2. Некорректная схема модели.
3. Можно зайти на закрытые ресурсы без авторизации.
4. При получении пользователя по `id` возвращается 500.
5. При обновлении профиля возвращается 500.
6. При обновлении аватара возвращается 500.
7. При удалении карточки возвращается 500.

**Можно лучше:**
1. Использовать встроенные хелперы mongoose для обработки несуществующей записи.
2. Использовать методы mongoose при сравнении идентификаторов.
3. Связать ответ с предметной областью.
4. Определять код ошибки непосредственно в месте возникновения.

2020-06-01 11:14 UTC, aarefiev commented on .env
> +JWT_SECRET=eb28135ebcfc17578f96d4d65b6c7871f2c803be4180c165061d5c2db621c51b
Нужно исправить: не игнорируются временные файлы.
https://github.com/VitalyBibik/sprint-backend/blob/534c1d63fd770cb80c2ae8882d8aa65b4fd2deb0/.gitignore#L9-L11
Если файл был создан ранее, чем был добавлен в список игнорирования, то он не будет удалён. Следует вручную удалить этот файл.

2020-06-01 11:14 UTC, aarefiev commented on controllers/cards.js
>        }
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.
В `mongoose` по-умолчанию методы, которые делают выборку значений из базы данных по какому-то
условию, возвращают `null` в случае отсутствия записи в базе данных. Для того, чтобы отловить эту ситуацию есть хелпер [`.orFail()`](https://mongoosejs.com/docs/api.html#query_Query-orFail).

Хелпер принимает функцию, которая выполняет _reject_ промиса. Если функция будет возвращать какое-то значение, оно будет передано в `.catch()` блок, если нет, то будет отправлено значение по-умолчанию.

Но это не всё. Ещё нужно корректно прокинуть код ошибки. Так как внутри `orFail()` хелпера можно передать любое значение, то я рекомендую создать отдельный модуль для ошибки. Модуль будет содержать класс, который наследует класс `Error` добавляя туда свойство, в котором будет определен HTTP код ошибки. Например для 404 он будет выглядеть так:
```js
// errors/notFoundError.js
class NotFoundError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 404;
  }
}

module.exports = NotFoundError;
```

Далее отправка ошибки в `orFail()` сводится к следующему:
```js
.orFail(() => new NotFoundError('Карточка не найдена'))
```

А передача кода уходит в `.catch()` блок:
```js
.catch((err) => {
  const statusCode = err.statusCode || 500;

  res.status(statusCode).send({
    message: statusCode === 500 ? 'Произошла ошибка' : err.message
  });
});
```

2020-06-01 11:14 UTC, aarefiev commented on controllers/cards.js
> +      if (card.owner._id.toString() !== req.user._id) {
Можно лучше: использовать методы `mongoose` при сравнении идентификаторов.
В библиотеке `mongoose` `card` - это экземпляр класса `Document`. У этого класса есть отдельный метод, который отвечает за проверку на равенство - это метод [`.equals()`](https://mongoosejs.com/docs/api.html#document_Document-equals). Его лучше использовать, потому что в этой практике поле `owner` - это объект, а `req.user._id` - это строка. И чтобы их сравнить нужно приводить типы. Если использовать метод библиотеки, то приведение типов делать не нужно.

2020-06-01 11:14 UTC, aarefiev commented on controllers/cards.js
> +      }
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-06-01 11:14 UTC, aarefiev commented on controllers/cards.js
> +        return res.status(404).send({ message: 'Like is empty' });
Можно лучше: связать ответ с предметной областью.
В случае, если карточка не найдена лайк не будет установлен. Поэтому лучше всего написать типа `Card is not found`.

2020-06-01 11:14 UTC, aarefiev commented on controllers/users.js
>      .then((user) => res.send({ data: user }))
Можно лучше: изменить список полей, которые будут отправлены при создании записи.
Насколько я понял, поиск по `id` был использован, потому что `password` всё же содержится в `createdUser`. Это одна из особенностей. Настройка `{ select: false }` работает только при получении записей.

Можно это обойти, например, создав отдельный метод:
```js
userSchema.methods.omitPrivate = function omitPrivate() {
  const obj = this.toObject();
  delete obj.password;
  return obj;
};
```

И далее
 ```suggestion
     .then((createdUser) => res.send({ data: createdUser.omitPrivate() }))
```

2020-06-01 11:14 UTC, aarefiev commented on controllers/users.js
> +    });
Можно лучше: определять код ошибки непосредственно в месте возникновения.
Как известно `.catch()` блок поймает все исключения, которые будут брошены в промисе или в `.then()` блоке. Это значит, что пользователь получит код 401 во всех случаях. Хотя, намного правильнее отдавать ему 401 код только в случае, когда его не удалось авторизовать (например, введена неверная пара email/пароль). А в других случаях отдавать коды ответов, соответствующие ситуации. Например, для ошибок на сервере отдавать 500.

Это реализуемо, если создать отдельный класс ошибки, в котором определить код ответа:
```js
// errors/unathorizedError.js
class UnathorizedError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 401;
  }
}

module.exports = UnathorizedError;
```

Эту ошибку нужно бросать непосредственно в месте возникновения:
https://github.com/VitalyBibik/sprint-backend/blob/534c1d63fd770cb80c2ae8882d8aa65b4fd2deb0/models/users.js#L47
и
https://github.com/VitalyBibik/sprint-backend/blob/534c1d63fd770cb80c2ae8882d8aa65b4fd2deb0/models/users.js#L52

Тогда в этом `.catch()` блоке это можно проверить так:
```js
.catch((err) => {
  const statusCode = err.statusCode || 500;

  res.status(statusCode).send({
    message: statusCode === 500 ? 'Произошла ошибка' : err.message
  });
});
```

2020-06-01 11:14 UTC, aarefiev commented on models/users.js
> +  select: false,
Нужно исправить: некорректная схема модели.
`select` нужно указать для поля `password`

2020-06-01 11:14 UTC, aarefiev commented on app.js
>  app.use('/', cardRoutes);
Нужно исправить: можно зайти на закрытые ресурсы без авторизации.
Ожидается, что если токен не был получен, то при обращении на роуты `/cards` и `/users` будет возвращено 401.

Дополнительно это приводит к тому, что функционал по работе с карточками всегда возвращает 500, тк `req.user._id` не определен.

2020-06-01 11:14 UTC, aarefiev commented on controllers/users.js
>  };
Нужно исправить: при получении пользователя по `id` возвращается 500.
Если указать существующий `id`, то в теле ответа приходит:
```json
{
    "message": "user.find is not a function"
}
```

Если несуществующий, то:
```json
{
    "message": "Cannot read property 'find' of null"
}
```

_в обоих случаях выше были указаны валидные `id`_

2020-06-01 11:14 UTC, aarefiev commented on controllers/users.js
>    const { name, about, avatar } = req.body;
Нужно исправить: при обновлении профиля возвращается 500.
Ответ с кодом 500:
```json
{
    "message": "Validation failed: avatar: Path `avatar` is required."
}
```

Обновление аватара по заданию происходит в отдельном роуте.

Если указать и аватар, то получаем другой ответ с кодом 500:
```json
{
    "message": "user.find is not a function"
}
```

При обновлении профиля идентификатор пользователя передаётся в токене. Мидлвара `auth.js` гарантирует, что в обновление токена попадут только пользователи если токен не просрочен. Поэтому отдельно проверять пользователя на существование в этом роуте не нужно.

2020-06-01 11:14 UTC, aarefiev commented on controllers/users.js
>    const { name, about, avatar } = req.body;
Нужно исправить: при обновлении аватара возвращается 500.
Ответ с кодом 500:
```json
{
    "message": "user.find is not a function"
}
```

2020-06-01 11:14 UTC, aarefiev commented on controllers/cards.js
>        const cardFind = card.find((item) => item.id === req.params.cardId);
Нужно исправить: при удалении карточки возвращается 500.
Ответ с кодом 500:
```json
{
    "message": "Cannot read property 'find' of null"
}
```

2020-06-01 11:27 UTC, VitalyBibik commented on controllers/cards.js
>        }
Это прямо то что меня волновало очень сильно, спасибо больше за пример

2020-06-01 11:36 UTC, VitalyBibik commented on controllers/cards.js
>        }
А сам класс Error будет принимать 
```
class  Error {
  constructor(message) {
    this.message = msg;
  }
}

module.exports = Error;
```

2020-06-04 11:46 UTC, VitalyBibik commented
Осталось:
 "Прокидывать ошибки через класс, 
переписать на async/await + orFail, 
equals вместо своих методов

2020-06-04 20:58 UTC, VitalyBibik commented on controllers/cards.js
> +      if (card.owner._id.toString() !== req.user._id) {
`      if (card.owner._id.equals(req.user._id)) {}`
Пытался сделать так, не помогло :( (http://mongodb.github.io/node-mongodb-native/api-bson-generated/objectid.html#equals)

2020-06-04 20:58 UTC, VitalyBibik commented on controllers/cards.js
> +      if (card.owner._id.toString() !== req.user._id) {
@aarefiev

2020-06-04 21:05 UTC, VitalyBibik commented
Здравствуйте, сделал 2 способами работу. Первое на then + через if else и сохранил как бекап.
2й способ. Это учесть ваши замечания "Можно лучше". Переписал все на Async await + orFail(), но возможно ошибся в обработке. Пробовал метод equals, но не получилось, получалось так, что система давала удалять карточку. Надеюсь этот код будет лучше, чем мой предыдущий, очень хочу адекватно и красиво написать этот спринт, спасибо вам большое за подробную проверку на 1 итерации. И я чуть профейлился, когда захотел делать коммиты атомарными и захапал лишнее случайно и в итоге коммиты не совсем атомарны.

2020-06-05 04:45 UTC, aarefiev commented on controllers/cards.js
> +      if (card.owner._id.toString() !== req.user._id) {
@VitalyBibik потому что метод `.equals()` есть у `owner`, а не у `_id`:
```js
if (card.owner.equals(req.user._id)) { }
```
Вот так будет работать.

2020-06-05 12:00 UTC, aarefiev requested changes
Очень хорошо. Осталось несколько ошибок.

**Нужно исправить:**
1. Ошибки линтинга.
2. При авторизации с неверной парой email/пароль возвращается 500.
3. Некорректный роут.
4. При создании карточки ошибка.
5. Невозможно удалить карточку.
6. Не игнорируются временные файлы.

2020-06-05 12:00 UTC, aarefiev commented on controllers/users.js
> +const NeedAuthError = require('../errors/NeedAuthError');
Нужно исправить: ошибки линтинга.
```bash
$ npx eslint --ext .js .

/home/jmi/work/ya-reviews/sprint-backend/app.js
  43:3  warning  Unexpected console statement  no-console

/home/jmi/work/ya-reviews/sprint-backend/controllers/users.js
   6:7   error  'NeedAuthError' is assigned a value but never used  no-unused-vars
  58:72  error  Missing semicolon                                   semi

/home/jmi/work/ya-reviews/sprint-backend/models/users.js
  44:44  warning  Unexpected unnamed function  func-names

✖ 4 problems (2 errors, 2 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

2020-06-05 12:00 UTC, aarefiev commented on models/users.js
> +        return Promise.reject(new Error('Invalid email or password'));
Нужно исправить: при авторизации с неверной парой email/пароль возвращается 500.
Ожидается что будет вернут ответ с кодом 401, а это в ошибке класса `NeedAuthError`.

2020-06-05 12:00 UTC, aarefiev commented on models/users.js
> +            return Promise.reject(new Error('Invalid email or password'));
Нужно исправить: при авторизации с неверной парой email/пароль возвращается 500.
Ожидается что будет вернут ответ с кодом 401, а это в ошибке класса `NeedAuthError`.

2020-06-05 12:00 UTC, aarefiev commented on routes/users.js
> +routes.post('/users', auth, getUsers);
Нужно исправить: некорректный роут.
Для получения списка пользователей нужно установить метод `GET`, а не `POST`.

2020-06-05 12:00 UTC, aarefiev commented on controllers/cards.js
> +      .orFail(() => new NotFoundError('Card list is empty'));
Нужно исправить: при создании карточки ошибка.
Метод `.orFail()` работает только при выборе записи из БД.

Здесь же этот метод является источником двух ошибок. 
Ошибка №1 - при создании карточки всегда возвращается 500.
Ошибка №2 - при попытке передать невалидные данные для создания карточки приводит к появлению ошибки в консоли:
```bash
(node:364875) UnhandledPromiseRejectionWarning: ValidationError: card validation failed: name: Path `name` (`1`) is shorter than the minimum allowed length (2).
    at new ValidationError (/home/jmi/work/ya-reviews/sprint-backend/node_modules/mongoose/lib/error/validation.js:31:11)
    at model.Document.invalidate (/home/jmi/work/ya-reviews/sprint-backend/node_modules/mongoose/lib/document.js:2563:32)
    at /home/jmi/work/ya-reviews/sprint-backend/node_modules/mongoose/lib/document.js:2385:17
    at /home/jmi/work/ya-reviews/sprint-backend/node_modules/mongoose/lib/schematype.js:1181:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:364875) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Это связано с тем, что `catch` блок обработал только одно исключение - вот это:
```bash
TypeError: Card.create(...).orFail is not a function
```

А после этого бала произведена попытка создать карточку и ппоявилось ещё одно исключение:
```bash
ValidatorError: Path `name` (`1`) is shorter than the minimum allowed length (2).
```
Вот оно уже было проигнорировано, так как было брощено асинхронно и не обработано.

2020-06-05 12:00 UTC, aarefiev commented on controllers/cards.js
> +    }
Нужно исправить: невозможно удалить карточку.
При попытке удалить свою карточку возвращается 403.

Также я в комментарии к прошлому ревью написал в чём была ошибка в работе с `.equals()`.

2020-06-05 12:00 UTC, aarefiev commented on .env
> +JWT_SECRET=eb28135ebcfc17578f96d4d65b6c7871f2c803be4180c165061d5c2db621c51b
Нужно исправить: не игнорируются временные файлы.
Не исправлено.
Ожидается, что он будет игнорироваться и будет удалён из репозитория.

В этой работе `.env` файл всегда для публичного сервера.

2020-06-05 13:55 UTC, VitalyBibik commented on controllers/cards.js
> +    }
Я не стал править, т.к. уже отправил на ревью и побоялся несостыковок в версиях

2020-06-05 17:13 UTC, VitalyBibik commented
Сейчас вроде работает, проблема была такая:
> Я создал потомков от Error для разных ошибок, переписал весь код на Async Await, чтобы использовать метод .orFail() => new SomeError('message')
> Далее при создании карточки у нас не может быть .orFail метода, следовательно нужно обрабатывать ошибки самому. Я придумал следующий способ
Написал функцию в начале так:
`const AccecDeniedError = require('./AccecDeniedError');
const InternalError = require('./InternalError');
const NeedAuthError = require('./NeedAuthError');
const NotFoundError = require('./NotFoundError');
const ValidationError = require('./ValidationError');
function FoundError(error, res) {
  if (error.name === 'ValidationError') {
    return res.status(400).send({ message: error.message });
  }
  if (error.name === 'CastError') {
    return res.status(400).send({ message: error.message });
  }
  return res.status(500).send({ message: error.message });
}
module.exports = FoundError;`
Но не смог прокидывать класс на отправку, я так подумал, что мне надо было тогда в класс делать доп переменную res и тогда уже оттуда прямо делать отправку, но тогда я бы сломал наверное .orFail(). 
Далее была такая идея:
>  Т.к. я не  использую здесь созданные классы (это плохо наверное), либо как вариант создать класс FoundError, который будет на вход принимать все эти классы + ошибку + res  и в 1 методе делать проверку всей этой каше и отправлять нужную ошибку.
Но в итоге сделал пока просто функцию FoundError, которая обрабатывает те ошибки, которые попадают в catch от orFail и вообще. Т.к. если есть ошибка валидации данных, где используется .orFail, то непонятно какая ошибка и что делать фронту. 
Я наверное тут намудрил сильно и ушел не туда, но мне понравилось то что я лучше в этом разобрался. 
Посоветовали celebrate поставить пакет, но я не стал, т.к. об этом в этом спринте ничего пока не было.  
P.S большое сообщение получилось) Но вам спасибо за терпение

2020-06-06 16:18 UTC, aarefiev requested changes
Хорошо. Но пропустили серьёзную ошибку. Прошу внимательнее проверять изменения.

**Нужно исправить:**
1. При авторизации с неверной парой email/пароль возвращается 500.
2. При бросании исключения с экземпляром класса отличным от `Error` всегда возвращается 500.

**Можно лучше:** реализовать централизованный обработчик ошибок.

2020-06-06 16:18 UTC, aarefiev commented on controllers/cards.js
> +    return FoundError(err, res);
Можно лучше: реализовать централизованный обработчик ошибок.
В общем сейчас сделано не совсем в традициях _Express_. Вся суть в том, что каждый запрос может быть обработан несколькими обработчиками подряд. За счет этого достигается возможность реализовать функционал в виде компонент. Сейчас же вы жёстко привязали код. Но в целом, вы приняли правильное решение, что убрали повторяющийся код в абстракцию, но остался вызов и он, к сожалению, повторяется.

Обработчик ошибок похож на обработчик несуществующего роута, но у него свои нюансы. О них узнаете в следующей работе.

2020-06-06 16:18 UTC, aarefiev commented on models/users.js
> +        return Promise.reject(new Error('Invalid email or password'));
Нужно исправить: при авторизации с неверной парой email/пароль возвращается 500.
Не исправлено. В одном месте исправили, а здесь нет. Если пользователя нет - значит `email`, который указали при авторизации не верен - значит 401.

2020-06-06 16:18 UTC, aarefiev commented on errors/FoundError.js
> +  return res.status(500).send({ message: error.message });
Нужно исправить: при бросании исключения с экземпляром класса отличным от `Error` всегда возвращается 500.
Новые классы ошибок как раз создавались для того, чтобы был единый принцип работы. Вы здесь забыли про то, что в этих классах уже указан код ответа, нужно его использовать.
Также рекомендую для 500 отправлять просто какой-то текст, типа `'Произошла ошибка'`.

```suggestion
  const statusCode = error.statusCode || 500;
  return res.status(statusCode).send({ 
    message: statusCode === 500 ? 'Произошла ошибка' : error.message,
  });
```

2020-06-06 18:31 UTC, VitalyBibik commented
@aarefiev , Централизованный обработчик ошибок будет таким получается
 В app.js я напишу
`app.use('/', myErrorHandler);`
Где Function MyErrorHandler(req, res, error, next)
{
// Cвятилище обработок всех ошибок
}
А там где остальное код добавится к примеру 
module.exports.getUser = async (req, res, next) => {
  try {
    const user = await User.findById(req.params.id)
      .orFail(() => new NotFoundError('User not found'));
    return res.send(user);
  } catch (err) {
    return next(err);
  }
};
и это потом обработается все в моем обработчике это вариант 1н

2020-06-06 18:33 UTC, aarefiev commented
Угу, но пока реализовывать не стоит. В этой задаче он не нужен. Всему своё время.

2020-06-06 18:34 UTC, VitalyBibik commented
2й вариант это
module.exports.getUser = async (req, res, next) => {
  try {
    const user = await User.findById(req.params.id)
      .orFail(() => new NotFoundError('User not found'));
    return res.send(user);
  } catch (err) {
    if (!FoundError(err, res) ){
next();
}
  }
};

2020-06-06 18:35 UTC, aarefiev commented
Нет, первый вариант. С ним есть нюанс в использовании, лучше сначала ознакомиться.

2020-06-06 18:36 UTC, VitalyBibik commented
Cпасибо огромное за такой быстрый ответ :)

2020-06-07 18:12 UTC, aarefiev approved these changes
Отлично. Ошибки исправлены, новых не обнаружено.
Работа принимается :rocket: .

2020-06-07 19:42 UTC, VitalyBibik commented
@aarefiev Спасибо вам большое за такое крутое ревью и обьяснения ноды :)

2020-06-07 19:51 UTC, merged